Repository enarx/frenetic, pull requests merged in 2019-07, with the labels that each got.

#25 Add GitPod configuration
  .gitpod.dockerfile
  .gitpod.yml
Labels: enhancement

#26 check for early drop of Coroutine
  src/lib.rs
Labels: bug

#24 Document primary API functions inline and in README
  README.md
  src/lib.rs
Labels: documentation

#27 Run tests on multiple architectures
  .travis.yml
Labels: enhancement
